---
- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts['userspace_bits'] == '32'

- name: Upgrade libseccomp2 on 32bit debian systems
  ansible.builtin.import_tasks: tasks/libseccomp_debian.yml
  when: ansible_facts['os_family'] == "Debian" and
        ansible_facts['userspace_bits'] == '32' and
        ansible_facts.packages['libseccomp2'][0]['version'] is version('2.4.4', '<')

- name: Clone internet-monitoring repo to Pi.
  ansible.builtin.git:
    repo: https://github.com/geerlingguy/internet-monitoring
    dest: ~/internet-monitoring/
    version: master
    accept_hostkey: true
    force: true
  become: false

# TODO: The first time this playbook is run, the `pi` user may not be added
# to the `docker` group, so this task may fail.
- name: Ensure internet-monitoring environment is running.
  community.docker.docker_compose:
    project_src: ~/internet-monitoring/
    build: false
  become: false
